name: Release Jupyter Workspace Manager
on:
  push:
    #    tags:
    #      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    container: golang:1.17.5
    steps:
      - uses: actions/checkout@v2

      - name: Get Version >> Environment
        run: |
          VERSIONED_NAME="jupyter-workspace-manager-$(cat VERSION)"
          echo "VERSIONED_NAME=$VERSIONED_NAME" >> "$GITHUB_ENV"
          echo "GZ_FILENAME=$VERSIONED_NAME.tar.gz" >> "$GITHUB_ENV"

      - name: Build
        run: make

      - name: Create Tar File
        run: |
          mkdir "${{ env.VERSIONED_NAME }}"
          tar -czvf "${{ env.GZ_FILENAME }}" "${{ env.VERSIONED_NAME }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.GZ_FILENAME }}
          path: ${{ env.GZ_FILENAME }}
          if-no-files-found: error
