name: Release Jupyter Workspace Manager
on:
  push:
    #    tags:
    #      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    container: golang:1.17.5
    steps:
      - name: Build
        run: ls -la
