name: Release Jupyter Workspace Manager
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    container: golang:1.17.5
    steps:
      - uses: actions/checkout@v2

      - name: Get Version >> Environment
        run: |
          VERSION="$(cat VERSION)"
          VERSIONED_NAME="jupyter-workspace-manager-$(cat VERSION)"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "VERSIONED_NAME=$VERSIONED_NAME" >> "$GITHUB_ENV"
          echo "GZ_FILENAME=$VERSIONED_NAME.tar.gz" >> "$GITHUB_ENV"

      - name: Build
        run: make

      - name: Create Tar File
        run: |
          mkdir "${{ env.VERSIONED_NAME }}"
          cp jupyter-workspace-manager "${{ env.VERSIONED_NAME }}"
          tar -czvf "${{ env.GZ_FILENAME }}" "${{ env.VERSIONED_NAME }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.GZ_FILENAME }}
          draft: true
          name: ${{ env.VERSION }}
